#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/
#for system behavior, performance, appearance, compatibility.

# Environment Variables (Setup)

env = XDG_SESSION_TYPE=wayland #use Wayland display server
env = ELECTRON_OZONE_PLATFORM_HINT=auto #Enable auto-hinting for Electron apps on Wayland.


# Nvidia GPU Configuration







# OpenGL Optimization for NVIDIA (optional)





# Cursor Settings
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24




#GTK & Application theme Settings



#Qt Platform Settings (Wayland and custom window decorations)




#Software Rendering




#For Disabling Animations for Performance Gains



#Cursor Behavior (Ensure hardware cursor is not used)
